language: node_js
node_js:
    - "0.10"
addons:
    code_climate:
        repo_token: 8deed161a6a093637bff10f922ec7b1f32f76f446523599687b49274f945a133
script: node_modules/karma/bin/karma start karma.conf.js --single-run
before_install:
    - export CHROME_BIN=chromium-browser
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
before_script:
    - npm install
after_script:
    - codeclimate-test-reporter < coverage/lcov.info
